=== DanZenti/indesign-import-to-contensis/indesign-doc-dtd-and-xml/xml-example-dtd.dtd
<!ELEMENT Magazine (Cover,Stories)>
<!ELEMENT Cover (CoverTitle,CoverSubtitle)>
<!ELEMENT CoverTitle (#PCDATA)>
<!ELEMENT CoverSubtitle (#PCDATA)>
<!ELEMENT Stories (Story*)>
<!ELEMENT Story (StoryHeading*,StoryIntroduction*,StorySubHeading*,StoryText*,StoryImage*,StorySubHeading*,StoryImage*,FeatureImage*)*>
<!ELEMENT StoryHeading (#PCDATA)>
<!ELEMENT StoryIntroduction (#PCDATA)>
<!ELEMENT StoryText (#PCDATA)>
<!ELEMENT StorySubHeading (#PCDATA)>
<!ELEMENT StoryImage EMPTY>
<!ATTLIST StoryImage href CDATA "">
<!ELEMENT FeatureImage EMPTY>
<!ATTLIST FeatureImage href CDATA "">

=== DanZenti/indesign-import-to-contensis/indesign-doc-dtd-and-xml/Tagged Indesign Booklet.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Magazine SYSTEM "C:\Sites\indesign-import-to-contensis\indesign-doc-dtd-and-xml\xml-example-dtd.dtd" [
]>
<Magazine><Cover><CoverTitle>Winner of the student choice awards</CoverTitle><CoverSubtitle>We’re ranked within the top 5 university’s for teaching excellence. </CoverSubtitle></Cover><Stories><Story><StoryHeading>Section heading item</StoryHeading><StoryIntroduction>Ibus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. </StoryIntroduction><StoryBody>  <StoryText>Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur?   Quis diatetur sitium fugit ium a sequundi bea cus auda quameni hillest oratati optate occaeperi delitib uscipitem hillecae ipidit, ommodio nsenis eturiam, il eaqui coreptam quam, ommolup tatest qui que rem id minverum utet il et moluptat aut aut et molorrum autem sam nusdantem renem reiciat ioreium, sam sinctot atibusciis magnis ullor sumetur, odis aut in enimusd aepraes vit rescill aborum vellam quiam, quia sincide lentur modis aut officiis natenihitium volupta epudit repti occabor enimagnam, veliamus deriberro tenda niatia quatur?  Us, tore, testias pellabo. Nam idendit, expellibus volorporit pore rereicitibus eatem. Doluptaque explaborem quam endit, ut voloribus, consequidias explit odit volorro rrovit pa que nobis alique corendis adi bea vendand enihitae ea ipidus experro mincil inctus, sapidus arum etur sum que num imod molupta qui andandandam inctio. Ehentusam, nissit harum eostiam quae. Hent ma poreperum voloreius iusa quate min nonseque nate doloremporem delestium untiaessed eum nonsecta pra vide num quo comniet, odiciam, vel maximaximin re vernam vid quas nobis el excearume et qui dolupissunti incitatatiis quaessit es atem fuga. Mus sus maio esti di optatur ad utendunt</StoryText>   <StorySubHeading>Sub heading item 1 </StorySubHeading><StoryText>bus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur?  </StoryText>  <StorySubHeading>Sub heading item 2 </StorySubHeading> <StoryText>Ibus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur?  </StoryText>  <StorySubHeading>Sub heading item 3 </StorySubHeading> <StoryText>Ibus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur? </StoryText>   <StorySubHeading>Sub heading item 4 </StorySubHeading><StoryText>bus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur?  </StoryText>  <StorySubHeading>Sub heading item 5 </StorySubHeading> <StoryText>Ibus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime derio dignia volorum re pel int atur? Quiam fugitae a volo to ipidebis est omnis re solorer cidello ribust laccullut as velis as idicatiunt volo eati nobisquatur, aceatia voluptio molor sitaspe rspictium veligentio conse num im laut rehendi gnihici tiatem id quates dolupta esenditas sum ea comnihit et eum simus a dolut libus molorerae pelitatis milia voluptaque nient litiis errum et que eic tenient et dentistiis atur?   Quis diatetur sitium fugit ium a sequundi bea cus auda quameni hillest oratati optate occaeperi delitib uscipitem hillecae ipidit, ommodio nsenis eturiam, il eaqui coreptam quam, ommolup tatest qui que rem id minverum utet il et moluptat aut aut et molorrum autem sam nusdantem renem reiciat ioreium, sam sinctot atibusciis magnis ullor sumetur, odis aut in enimusd aepraes vit rescill aborum vellam quiam, quia sincide lentur modis aut officiis natenihitium volupta epudit repti occabor enimagnam, veliamus deriberro tenda niatia quatur?  Us, tore, testias pellabo. Nam idendit, expellibus volorporit pore rereicitibus eatem. Doluptaque explaborem quam endit, ut voloribus, consequidias explit odit volorro rrovit pa que nobis alique corendis adi bea vendand enihitae ea ipidus experro mincil inctus, sapidus arum etur sum que num imod molupta qui andandandam inctio. Ehentusam, nissit harum eostiam quae. Hent ma poreperum voloreius iusa quate min nonseque nate doloremporem delestium untiaessed eum nonsecta pra vide num quo comniet, odiciam, vel maximaximin re vernam vid quas nobis el excearume et qui dolupissunti incitatatiis quaessit es atem fuga. Mus sus maio esti di optatur ad utendunt</StoryText>   <StorySubHeading>Sub heading item 6 </StorySubHeading><StoryText>bus aut ut eatibusda volum vel eos maximi, soluptae laborer ionsequiae. Nam, que volorporro cusdandelis nobis nonsed ut estionsedis nonsectio comnisc iumqui comnihit et ut la volorit es dellam exerrovitem am, omniet ex es accum quam nonsequossum qui sitas andionem fugiatus nobisque sed qui culparchil inim eatquidi reped quo debis dolecature es pro ommolor mo officident fuga. Eque volorrum que nones es doluptate es necea coriate mporestius intibusciis andictes entiorio. Et essequi delignis consequi optatur?  Am, am, alitatur aute ide sam voluptat volore plique volluptur, et lant, ame venient el ime de
